name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        coverage run -m pytest python_use_example_test.py
    - name: Generate coverage report
      run: |
        coverage report
        coverage html
        coverage xml
    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
    - name: Convert coverage report to markdown
      run: |
        pip install genbadge[coverage]
        genbadge coverage -i coverage.xml -o coverage.md
    - name: Post coverage report as comment
      uses: marocchino/sticky-pull-request-comment@v2
      permissions:
        pull-requests: write
      with:
        header: coverage
        path: coverage.md
